Month7/step1
leondasferras/react-burger pull request #1
Opened 2022-05-04 04:22 UTC by leondasferras

2022-05-04 07:10 UTC, andryxxa93 requested changes
Проделана большая работа!

Вы хорошо структурировали документ. Стили использованы правильно. Проект практически полностью соответствует макету в figma. Хорошее использование функи

Однако есть несколько замечаний:

1) Не реализовано модальное окно с отображением информации об ингредиенте и модальное окно с отображением деталей заказа.
2) Не реализован запрос на получение ингредиентов с сервера - https://norma.nomoreparties.space/api/ingredients.
3) Для компонентов которые принимают props нет типизации через PropsTypes.
4) Для элементов в массиве нет ключа key.
5) Компонент BurgerIngredients не соответствует макету в figma.

Можно улучшить: 
1) Поправить форматирование кода
2) Использовать для меню навигации тег nav 
3) Изменить абстрактные названия переменных на более конкретные
4) Убрать повторения верстки в отдельные компоненты и переиспользовать

Напомню, чтобы ваша работа была принята, необходимо исправить все замечания помеченные как "Необходимо исправить".
Замечания "Можно улучшить" исправлять не обязательно, но они позволят сделать ваш код чище и избежать ошибок в будущем.

Удачных правок!

2022-05-04 07:10 UTC, andryxxa93 commented on src/App.jsx
> +// export default App;
Можно улучшить: неиспользуемые файлы лучше удалять

2022-05-04 07:10 UTC, andryxxa93 commented on src/App.tsx
> +</main>
Можно улучшить: нарушено форматирование кода - проблемы с отступами и в некоторых местах, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Практически все современные редакторы умеют автоматически форматировать код. В vscode для этого **достаточно нажать F1 и в выпадающем списке выбрать пункт Format Document**.
 Постарайтесь использовать автоматическое форматирование, это сильно экономит время, а Ваш код будет всегда красив. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

2022-05-04 07:10 UTC, andryxxa93 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +             </div>
Необходимо исправить: У каждого элемента массива должен быть ключ (key). Ключ - это специальный строковый атрибут, который нужно указывать при создании списка элементов.

Ключи помогают реакту определять, какие элементы были изменены, добавлены или удалены. Их необходимо указывать, чтобы реакт мог сопоставлять элементы массива с течением времени.

В качестве key следует использовать уникальный _id, который есть у каждой карточки[https://ru.reactjs.org/docs/lists-and-keys.html#gatsby-focus-wrapper](https://ru.reactjs.org/docs/lists-and-keys.html#gatsby-focus-wrapper)

2022-05-04 07:10 UTC, andryxxa93 commented on src/components/BurgerIngredients/IngredientsList/IngredientsList.jsx
> +    }))
Отлично! Рендеринг верстки вынесен в отдельную функцию!

2022-05-04 07:10 UTC, andryxxa93 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +        <Tab value="one" active={current === 'one'} onClick={setCurrent}>
Можно улучшить:  абстрактные названия по типу "one", "data" и т.п. лучше не использовать, лучше называть вещи более конкретно, это позволит лучше понимать код.

2022-05-04 07:10 UTC, andryxxa93 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +          </section>
Можно улучшить: тут верстка повторяется 3 раза, меняется только текст и type. Её можно вынести в отдельный компонент и переиспользовать.

2022-05-04 07:10 UTC, andryxxa93 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +};
Хорошо! Правильно использована типизация props!

2022-05-04 07:10 UTC, andryxxa93 commented on src/components/BurgerIngredients/IngredientsList/IngredientsList.jsx
> +
Можно улучшить: ненужное пустое пространство

2022-05-04 07:10 UTC, andryxxa93 commented on src/components/AppHeader/AppHeader.jsx
> +    </section>
Можно улучшить: для меню навигации в html есть тег nav, в таких местах лучше использовать его

2022-05-13 17:29 UTC, leondasferras commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +             </div>
+

2022-05-14 09:15 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect, propTypes и подписку на нажатие на клавишу ESC. 

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
1) Привести расположение и размер модального окна в соответствие с макетом figma.
2)  Вынести компонент App в отдельную директорию в components. 
3) Привести в соответствие с макетом высоту компонента конструктора. 

В pull request вы найдете комментарии с более подробным описанием проблемы и возможным путем её решения.
В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок.

Удачных правок!

2022-05-14 09:15 UTC, andryxxa93 commented on src/App.jsx
> +import React, { useEffect, useState } from "react";
**Необходимо исправить**
Компонент App необходимо так же поместить в директорию components. Так же желательно именовать директории в стиле kebab-case. Это позволит избежать проблем с гитхабом при переименовании директории в будущем.

2022-05-14 09:15 UTC, andryxxa93 commented on src/App.jsx
> +    getIngredientsData();
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2022-05-14 09:15 UTC, andryxxa93 commented on src/App.jsx
> +        .catch(() => console.log("Ошибка при запросе с сервера!"))
**Можно улучшить**
Console.log нужен только для процесса разработки, перед сдачей проекта его нужно удалять

2022-05-14 09:15 UTC, andryxxa93 commented on src/components/Modal/Modal.module.css
> +}
**Необходимо исправить**
Модальное окно должно располагаться посредине экрана. Сейчас оно находится в правом нижнем углу.
Чтобы это исправить можно добавить такие стили:
```
left: 50%;
top: 50%;
transform: translateX(-50%) translateY(-50%);
```
https://html5book.ru/css3-transform/
<img width="1440" alt="Снимок экрана 2022-05-14 в 11 50 42" src="https://user-images.githubusercontent.com/60173362/168418624-b2617246-877e-4e1e-a3a3-b3371aec3389.png">

2022-05-14 09:15 UTC, andryxxa93 commented on src/App.jsx
> +  };
Здорово, что вы реализовали закрытие модальных окон помощью клика на оверлей и ESC!

2022-05-14 09:15 UTC, andryxxa93 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +export const BurgerConstructor = (props) => {
**Можно улучшить**
Здесь и в коде других компонентов, лучше не писать каждый раз `props`, а использовать деструктуризацию, достав все необходимые данные из пропсов один раз. Это сделает код более понятным. https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta

2022-05-14 09:15 UTC, andryxxa93 commented on src/components/BurgerConstructor/BurgerConstructor.module.css
> +}
**Необходимо исправить**
Высота компонента конструктора не соответствует макету из figma.
Как должно выглядеть - 
<img width="357" alt="Снимок экрана 2022-05-14 в 12 01 27" src="https://user-images.githubusercontent.com/60173362/168418979-0f5a528d-537c-45d5-a9fe-3cb6123a733b.png">
Как выглядит сейчас -
<img width="584" alt="Снимок экрана 2022-05-14 в 12 02 10" src="https://user-images.githubusercontent.com/60173362/168418992-2093a75b-793b-4ba7-894a-0284f9864f4a.png">

2022-05-14 09:15 UTC, andryxxa93 commented on src/components/BurgerIngredients/IngredientsList/Ingredient/Ingredient.jsx
> +  data: ingredientPropType,
**Можно лучше**
Желательно избегать абстрактных названий типа `data`. Название должно сообщать о содержимом переменной.

2022-05-14 09:15 UTC, andryxxa93 commented on src/components/IngredientDetails/IngredientDetails.jsx
> +          <p className='text text_type_digits-default text_color_inactive'>{props.ingredientData.calories}</p>
**Можно улучшить**
Тут есть повторение верстки, её желательно вынести в отдельный компонент и переиспользовать

2022-05-14 09:15 UTC, andryxxa93 commented on src/components/OrderDetails/OrderDetails.module.css
> +  text-shadow: 0px 0px 16px rgba(51, 51, 255, 0.25), 0px 0px 8px rgba(51, 51, 255, 0.25), 0px 4px 32px rgba(51, 51, 255, 0.5);
Можно улучшить
Когда используется нулевое значение, то единицы измерения (px) ставить не нужно

2022-05-14 20:14 UTC, andryxxa93 approved these changes
Отлично! Все замечания учтены. Ваша работа принята!

Удачного продолжения обучения!

2022-10-30 16:17 UTC, merged